In [ ]:
# NumPyをインポートするコードを記述する
import numpy as np

# AとBの行列を格納する多次元配列のコードを記述する
A = np.array([[0, 1], [2, 3], [4, 5]])
B = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])

# Step3.の計算結果を表示するコードを記述する
print("A=")
print(A)
print("B=")
print(B)

# 行列の要素の最大値を求めるコードを記述する
max_A = np.max(A)
max_B = np.max(B)

print("Aの最大値:", max_A)
print("Bの最大値:", max_B)


A=
[[0 1]
 [2 3]
 [4 5]]
B=
[[0 1 2 3]
 [4 5 6 7]]
Aの最大値: 5
Bの最大値: 7
